# Generated by Django 6.0.3 on 2026-04-15 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='food', max_length=20, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonarExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=191)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('share_contact', models.BooleanField(default=True)),
                ('food_category', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Packed', 'Packed'), ('Raw', 'Raw')], default='Veg', max_length=20)),
                ('state', models.CharField(default='Kerala', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NGOExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('joindate', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=40)),
                ('share_contact', models.BooleanField(default=True)),
                ('accepted_category', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Packed', 'Packed'), ('Raw', 'Raw')], default='Veg', max_length=20)),
                ('state', models.CharField(default='Kerala', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=191)),
                ('companyName', models.CharField(max_length=191)),
                ('number', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('foodName', models.CharField(max_length=191)),
                ('foodImage', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('inputState', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('Listed', 'Listed'), ('Claimed', 'Claimed'), ('Picked Up', 'Picked Up'), ('Delivered', 'Delivered')], default='Listed', max_length=20)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('donationdate', models.DateField(auto_now_add=True)),
                ('food_category', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Packed', 'Packed'), ('Raw', 'Raw')], default='Veg', max_length=20)),
                ('state', models.CharField(default='Kerala', max_length=50)),
                ('donar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.donarextra')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.ngoextra')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngoname', models.CharField(max_length=191)),
                ('foodName', models.CharField(max_length=191)),
                ('mobile', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.donation')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ngoextra')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('transaction_id', models.CharField(max_length=100)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.claim')),
                ('donar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.donarextra')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.volunteer'),
        ),
    ]
