# Generated by Django 6.0.3 on 2026-04-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donarextra',
            name='photo',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='ngoextra',
            name='photo',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
